/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as OrdensServicoRouteImport } from './routes/ordens-servico'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensServicoRoute = OrdensServicoRouteImport.update({
  id: '/ordens-servico',
  path: '/ordens-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/ordens-servico': typeof OrdensServicoRoute
  '/produtos': typeof ProdutosRoute
  '/clientes/$id': typeof ClientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/ordens-servico': typeof OrdensServicoRoute
  '/produtos': typeof ProdutosRoute
  '/clientes/$id': typeof ClientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/ordens-servico': typeof OrdensServicoRoute
  '/produtos': typeof ProdutosRoute
  '/clientes/$id': typeof ClientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/ordens-servico'
    | '/produtos'
    | '/clientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clientes' | '/ordens-servico' | '/produtos' | '/clientes/$id'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/ordens-servico'
    | '/produtos'
    | '/clientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  OrdensServicoRoute: typeof OrdensServicoRoute
  ProdutosRoute: typeof ProdutosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens-servico': {
      id: '/ordens-servico'
      path: '/ordens-servico'
      fullPath: '/ordens-servico'
      preLoaderRoute: typeof OrdensServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRouteWithChildren,
  OrdensServicoRoute: OrdensServicoRoute,
  ProdutosRoute: ProdutosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
